# Generated by Django 5.2.4 on 2025-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('renda_familiar', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
    ]
