# Generated by Django 5.2.4 on 2025-07-16 21:26

import back_teste_wittel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(help_text='Até 150 caracteres.', max_length=150)),
                ('cpf', models.CharField(help_text='11 dígitos (Sem pontuação).', max_length=11, primary_key=True, serialize=False, validators=[back_teste_wittel.validators.validate_cpf])),
                ('data_nascimento', models.DateField(validators=[back_teste_wittel.validators.date_not_future])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('renda_familiar', models.DecimalField(decimal_places=2, help_text='Até 150 caracteres.', max_digits=65)),
            ],
        ),
    ]
