# Generated by Django 5.2.4 on 2025-07-20 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_teste_wittel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='renda_familiar',
            field=models.DecimalField(decimal_places=2, help_text='Até 150 caracteres.', max_digits=65, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
